data_config:
  train_dir: C:\Users\A\Desktop\CS675\Project\data\taobao\train.pkl
  valid_dir: C:\Users\A\Desktop\CS675\Project\data\taobao\dev.pkl
  test_dir: C:\Users\A\Desktop\CS675\Project\data\taobao\test.pkl
  data_format: pkl
  data_specs:
    num_event_types: 17
    pad_token_id: 17
    padding_side: right
    truncation_side: right
    padding_strategy: null
    truncation_strategy: null
    max_len: null
base_config:
  stage: train
  backend: torch
  dataset_id: taobao
  runner_id: std_tpp
  model_id: RMTPP3
  base_dir: ./checkpoints/
  specs:
    log_folder: ./checkpoints/30976_17324_241204-175347
    saved_model_dir: ./checkpoints/30976_17324_241204-175347\models\saved_model
    saved_log_dir: ./checkpoints/30976_17324_241204-175347\log
    output_config_dir: ./checkpoints/30976_17324_241204-175347\RMTPP3_train_taobao_output.yaml
model_config:
  rnn_type: LSTM
  hidden_size: 32
  time_emb_size: 16
  num_layers: 2
  sharing_param_layer: false
  loss_integral_num_sample_per_step: 20
  dropout_rate: 0.0
  use_ln: false
  thinning:
    num_seq: 10
    num_sample: 1
    num_exp: 500
    look_ahead_time: 10
    patience_counter: 5
    over_sample_rate: 5
    num_samples_boundary: 5
    dtime_max: 5
    num_step_gen: 1
  num_event_types_pad: 18
  num_event_types: 17
  event_pad_index: 17
  model_id: RMTPP3
  pretrained_model_dir: null
  gpu: -1
  model_specs: {}
trainer_config:
  seed: 2019
  gpu: -1
  batch_size: 256
  max_epoch: 200
  shuffle: false
  optimizer: adam
  learning_rate: 0.001
  valid_freq: 1
  use_tfb: false
  metrics:
  - acc
  - rmse
