data_config:
  train_dir: C:\Users\A\Desktop\CS675\Project\data\retweet\train.pkl
  valid_dir: C:\Users\A\Desktop\CS675\Project\data\retweet\dev.pkl
  test_dir: C:\Users\A\Desktop\CS675\Project\data\retweet\test.pkl
  data_format: pkl
  data_specs:
    num_event_types: 3
    pad_token_id: 3
    padding_side: right
    truncation_side: right
    padding_strategy: null
    truncation_strategy: null
    max_len: null
base_config:
  stage: gen
  backend: torch
  dataset_id: retweet
  runner_id: std_tpp
  model_id: RMTPP
  base_dir: ./checkpoints/
  specs:
    log_folder: ./checkpoints/34596_14872_241204-132722
    saved_model_dir: ./checkpoints/34596_14872_241204-132722\models\saved_model
    saved_log_dir: ./checkpoints/34596_14872_241204-132722\log
    output_config_dir: ./checkpoints/34596_14872_241204-132722\RMTPP_gen_retweet_output.yaml
model_config:
  rnn_type: LSTM
  hidden_size: 32
  time_emb_size: 16
  num_layers: 2
  sharing_param_layer: false
  loss_integral_num_sample_per_step: 20
  dropout_rate: 0.0
  use_ln: false
  thinning:
    num_seq: 10
    num_sample: 1
    num_exp: 500
    look_ahead_time: 10
    patience_counter: 5
    over_sample_rate: 5
    num_samples_boundary: 5
    dtime_max: 5
    num_step_gen: 10
  num_event_types_pad: 4
  num_event_types: 3
  event_pad_index: 3
  model_id: RMTPP
  pretrained_model_dir: ./checkpoints/12844_29460_241204-124759/models/saved_model
  gpu: -1
  model_specs: {}
trainer_config:
  seed: 2019
  gpu: -1
  batch_size: 256
  max_epoch: 200
  shuffle: false
  optimizer: adam
  learning_rate: 0.001
  valid_freq: 1
  use_tfb: false
  metrics:
  - acc
  - rmse
