data_config:
  train_dir: C:\Users\A\Desktop\CS675\Project\data\taobao\train.pkl
  valid_dir: C:\Users\A\Desktop\CS675\Project\data\taobao\dev.pkl
  test_dir: C:\Users\A\Desktop\CS675\Project\data\taobao\test.pkl
  data_format: pkl
  data_specs:
    num_event_types: 17
    pad_token_id: 17
    padding_side: right
    truncation_side: right
    padding_strategy: null
    truncation_strategy: null
    max_len: null
base_config:
  stage: gen
  backend: torch
  dataset_id: taobao
  runner_id: std_tpp
  model_id: RMTPP
  base_dir: ./checkpoints/
  specs:
    log_folder: ./checkpoints/39240_23976_241204-194707
    saved_model_dir: ./checkpoints/39240_23976_241204-194707\models\saved_model
    saved_log_dir: ./checkpoints/39240_23976_241204-194707\log
    output_config_dir: ./checkpoints/39240_23976_241204-194707\RMTPP_gen_taobao_output.yaml
model_config:
  rnn_type: LSTM
  hidden_size: 32
  time_emb_size: 16
  num_layers: 2
  sharing_param_layer: false
  loss_integral_num_sample_per_step: 20
  dropout_rate: 0.0
  use_ln: false
  thinning:
    num_seq: 10
    num_sample: 1
    num_exp: 500
    look_ahead_time: 10
    patience_counter: 5
    over_sample_rate: 5
    num_samples_boundary: 5
    dtime_max: 5
    num_step_gen: 10
  num_event_types_pad: 18
  num_event_types: 17
  event_pad_index: 17
  model_id: RMTPP
  pretrained_model_dir: ./checkpoints/36392_33772_241204-182605/models/saved_model
  gpu: -1
  model_specs: {}
trainer_config:
  seed: 2019
  gpu: -1
  batch_size: 256
  max_epoch: 200
  shuffle: false
  optimizer: adam
  learning_rate: 0.001
  valid_freq: 1
  use_tfb: false
  metrics:
  - acc
  - rmse
